### ISSUE TITLE
Add a check to copy only systemd or upstart configuration

### ISSUE THREAD

**Issue by javaguirre** [javaguirre/ghost-ansible#4]
Check which service is running and only add the correct service.

**Comment by javaguirre** [comment]
I've been studying the problem, and I think the best would be a variable controlled by the user (default upstart), and then according to that variable deploy one of the configurations.

Controlling if the system is using systemd or upstart and It's being used is trickier and a hassle.

What do you think @brianwawok ?

**Comment by brianwawok** [comment]
Is this too clever?

http://unix.stackexchange.com/a/196222/116544

You can look at the pid1 to find out init vs upstart vs systemd

**Comment by javaguirre** [comment]
Maybe we can do something with that, using [Ansible stat](http://docs.ansible.com/ansible/stat_module.html) and saving the result in a variable we could later use in a `when` condition.

Do you want to give It a try?

**Comment by brianwawok** [comment]
@javaguirre I moved on from ghost for a bit, when I circle back if this is still open I will give it a look

**Comment by javaguirre** [comment]
No problem! I'll give it a try too if I have time. Thank you!
